# kubernetes deployment template
# prepare a namespace on your cluster first like libretranslate-prod
apiVersion: v1
kind: ConfigMap
metadata:
  name: libretranslate-config
data:
# list loaded languages or leave empty to load all
  langs: ""
  ltapikey: "Q5OayeSDEmxdxE4WVTqmVaAI2va3FVNT69bZM-Vgk-8tD20"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      labels:
        app: libretranslate
    spec:
      containers:
      - name: libretranslate
        image: 769215394510.dkr.ecr.us-west-2.amazonaws.com/libretranslate:{tag}
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
          requests:
            memory: "5Gi"
            cpu: "3000m"
        livenessProbe:
            httpGet:
                scheme: HTTP
                path: /languages
                port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
        ports:
        - containerPort: 5000
        env:
        #- name: "LT_LOAD_ONLY"
        #  valueFrom:
        #    configMapKeyRef:
        #      name: libretranslate-config
        #      key: langs
        - name: "TRANSLATE_KEY"
          valueFrom:
            configMapKeyRef:
              name: libretranslate-config
              key: ltapikey
---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate-svc
spec:
  selector:
    app: libretranslate
  ports:
  - port: 5000
    targetPort: 5000
